USE [kpZleceniaWeb]
GO

/****** Object:  Table [dbo].[AppCombo]    Script Date: 02.11.2024 02:31:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AppCombo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Forms] [varchar](50) NOT NULL,
	[Combo] [varchar](50) NOT NULL,
	[Zrodlo] [varchar](2000) NOT NULL,
 CONSTRAINT [PK_AppCombo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


